"""Optimization planning contracts that precede future configuration search."""

from extstats_advisor.optimization.artifact import (
    inspect_singleton_profile,
    load_singleton_profile,
    validate_singleton_profile,
    write_singleton_profile,
)
from extstats_advisor.optimization.budget import (
    DEFAULT_WALL_CLOCK_SECONDS,
    OPTIMIZATION_BUDGET_CONTRACT,
    OptimizationBudget,
)
from extstats_advisor.optimization.plan import (
    OPTIMIZATION_PLAN_FORMAT_VERSION,
    OPTIMIZATION_PLAN_V2_FORMAT_VERSION,
    SCREENING_POLICY,
    OptimizationPlan,
    ScreenedCandidate,
    create_optimization_plan,
)
from extstats_advisor.optimization.plan_artifact import (
    inspect_optimization_plan,
    load_optimization_plan,
    validate_optimization_plan,
    write_optimization_plan,
)
from extstats_advisor.optimization.search import (
    GREEDY_ADD_SEARCH_POLICY,
    INCREMENTAL_GREEDY_ADD_SEARCH_POLICY,
    SEARCH_RESULT_FORMAT_VERSION,
    SEARCH_RESULT_V2_FORMAT_VERSION,
    TERMINATION_ALL_SELECTED,
    TERMINATION_BUDGET_BEFORE_ROUND,
    TERMINATION_BUDGET_INCOMPLETE_ROUND,
    TERMINATION_LOCAL_OPTIMUM,
    TERMINATION_MAX_STATISTICS_COUNT,
    AcceptedMove,
    CompletedSearchRound,
    PlannerIdentity,
    SearchDeadline,
    SearchEvaluation,
    SearchResult,
    greedy_add_search,
    greedy_add_search_incremental,
)
from extstats_advisor.optimization.search_artifact import (
    inspect_search_result,
    load_search_result,
    validate_search_result,
    write_search_result,
)
from extstats_advisor.optimization.singleton import (
    SINGLETON_PRECEDENCE_POLICY,
    SINGLETON_PROFILE_FORMAT_VERSION,
    BaselineProfile,
    CandidateSingletonProfile,
    SingletonProfile,
    profile_singletons,
    profile_singletons_full_workload_reference,
    validate_nonincident_estimates_unchanged,
)

__all__ = [
    "DEFAULT_WALL_CLOCK_SECONDS",
    "GREEDY_ADD_SEARCH_POLICY",
    "INCREMENTAL_GREEDY_ADD_SEARCH_POLICY",
    "OPTIMIZATION_BUDGET_CONTRACT",
    "OPTIMIZATION_PLAN_FORMAT_VERSION",
    "OPTIMIZATION_PLAN_V2_FORMAT_VERSION",
    "SCREENING_POLICY",
    "SEARCH_RESULT_FORMAT_VERSION",
    "SEARCH_RESULT_V2_FORMAT_VERSION",
    "SINGLETON_PRECEDENCE_POLICY",
    "SINGLETON_PROFILE_FORMAT_VERSION",
    "TERMINATION_ALL_SELECTED",
    "TERMINATION_BUDGET_BEFORE_ROUND",
    "TERMINATION_BUDGET_INCOMPLETE_ROUND",
    "TERMINATION_LOCAL_OPTIMUM",
    "TERMINATION_MAX_STATISTICS_COUNT",
    "AcceptedMove",
    "BaselineProfile",
    "CandidateSingletonProfile",
    "CompletedSearchRound",
    "OptimizationBudget",
    "OptimizationPlan",
    "PlannerIdentity",
    "ScreenedCandidate",
    "SearchDeadline",
    "SearchEvaluation",
    "SearchResult",
    "SingletonProfile",
    "create_optimization_plan",
    "greedy_add_search",
    "greedy_add_search_incremental",
    "inspect_optimization_plan",
    "inspect_search_result",
    "inspect_singleton_profile",
    "load_optimization_plan",
    "load_search_result",
    "load_singleton_profile",
    "profile_singletons",
    "profile_singletons_full_workload_reference",
    "validate_nonincident_estimates_unchanged",
    "validate_optimization_plan",
    "validate_search_result",
    "validate_singleton_profile",
    "write_optimization_plan",
    "write_search_result",
    "write_singleton_profile",
]
